apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: httpserver:v1.0
          imagePullPolicy: Always
          env: # 定义环境变量，配置和代码分离
          - name: ENV_VERSION
            valueFrom:
              configMapKeyRef:
                name: httpserver-evn-config
                key: ENV_VERSION
          resources: # 资源请求和Qos保证：Burstable
            limits:
              memory: 300Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
          - name: logPath
            mountPath: /log
          readinessProbe: # 优雅启动（探活）
            httpGet:
              ### this probe will fail with 404 error code
              ### only httpcode between 200-400 is retreated as success
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 2
        imagePullSecrets: ### Pull image from a Private Rigistry Docker Hub
        - name: regcred
        volumes:
        - name: logPath
          emptyDir: {}