apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpsserver
spec:
  hosts:
    - httpsserver
  http:
    - match:
      - port: 443
      - headers:
            user:
              exact: jesse
      - uri:
          exact: "/hello/bar"
      rewrite:
        uri: "/bar"
      route:
        - destination:
            host: httpsserver
            subset: v2
            port:
              number: 80
    - route:
      - destination:
          host: httpsserver
          subset: v1
          port:
            number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpsserver
spec:
  host: httpserver.securesvc.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
    tls:
      mode: SIMPLE
      credentialName: cncamp-credential
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN